### ISSUE TITLE
RDT better command line interface usability

### ISSUE THREAD

**Issue by dpinney** [lanl-ansi/micot#12]
Couple requests:

1. Error out and show correct usage on invalid arguments. I.e. I ran java -jar micot-rdt.jar -c input.json -o new_out.json, it ran with no warnings, but it should probably tell me -o is invalid and then list the valid ones (I was looking for -e).

2. Add a -h flag that displays the command line usage.

3. Update docs to clearly list all command line options. Right now they're in the wiki under the 2nd set (?) of Linux install instructions.

**Comment by rb004f** [comment]
Completed
