### ISSUE TITLE
RDT - load lost output

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/micot#31]
Quoteth @dpinney 

Is it possible to list the loads that were lost in the GFM output?

This would simplify post-run analysis.

If this isn't possible inside GFM, it's something that could be done elsewhere (i.e. by comparing damaged lines from GFM to source circuit model).

**Comment by rb004f** [comment]
RDT reports the load that is served at each location in each scenario (scenario_solution block).  So, the load dropped at each location is the delta between the input load value and the served value.  We could report both.

**Comment by dpinney** [comment]
If it's economical to implement, we'd like to request support for both. Utilities will want to see load lost, i.e. meters involved in an outage.

**Comment by rb004f** [comment]
Completed
