### ISSUE TITLE
Failure of installation of dependent libraries on unbuntu 18.10

### ISSUE THREAD

**Issue by OppenheimerAndTheMartians** [lanl-ansi/micot#38]
Hello,

I'm currently struggling with a bug being caused when using your software. There's a certain file-rdtOutput.json-that isn't being generated automatically like it should be. We think it might be an issue with the installation of scipLibrary.so. Is it supposed to be in the /usr/local/bin or /lib path?

This isn't occurring with anybody else at NRECA, so it seems like it is probably an issue with my system. Do you have any idea what might be going on? Also, can you make sure to update the installation docs? There's nothing in the Ubuntu repo for libreadline6 or libreadline6-dev.

**Comment by rb004f** [comment]
Thanks for the questions, and let me take a moment to make sure I understand the issue.

1. First, the RDT output filename is a required field to run the software (the -e argument listed here https://github.com/lanl-ansi/micot/wiki/Resilient-Design-Executable)

2. The SCIP installation is the most brittle part of the process of getting RDT up and running from a new machine.  The instructions for doing so here (tested on Ubuntu 16.04.1) https://github.com/lanl-ansi/micot under the heading "[Optional] SCIP Installation" There is a list of libraries that should be installed through apt-get (including readline and readline-dev).  Has Ubuntu stopped supporting these libraries?

3. If you have console trace from RDT that will help us track down the issue.

**Comment by OppenheimerAndTheMartians** [comment]
1) Yes, I get this error when I execute this command. The error might be caused in a private repo of ours, so I'm going to consult with my boss with it, then ask you if necessary.

2) I don't know whether they supported them in the first place or whether they've stopped, but they aren't there. 

3) Sure. Here's the consult output:

Using configuration file: /home/workstation/Desktop/Work/omf/omf/data/Model/admin/Automated Testing of resilientDist/rdtInput.json
Performing Data Validation Checks on RDT input...
Data Validation Checks on Line Damage Status completed... success
Data Validation Checks on Line Hardening options completed... fail
	Some lines are not allowed to be hardened. RDT cannot guarantee there will be a feasible solution.
	The following lines cannot be hardened
		 A_node733-734 A_node734-737 A_node734-710 A_node737-738 A_node744-728 A_node781-701 A_node744-729 B_node701-702 B_node702-705 B_node702-713 B_node702-703 B_node703-727 B_node703-730 B_node704-714 B_node704-720 B_node705-742 B_node705-712 B_node706-725 B_node707-724 B_node707-722 B_node708-733 B_node708-732 B_node709-731 B_node709-708 B_node710-735 B_node710-736 B_node711-741 B_node711-740 B_node713-704 B_node714-718 B_node720-707 B_node720-706 B_node727-744 B_node730-709 B_node733-734 B_node734-737 B_node734-710 B_node737-738 B_node738-711 B_node744-728 B_node781-701 B_node744-729 C_node701-702 C_node702-705 C_node702-713 C_node702-703 C_node703-727 C_node703-730 C_node704-714 C_node704-720 C_node705-742 C_node705-712 C_node706-725 C_node707-724 C_node707-722 C_node708-733 C_node708-732 C_node709-731 C_node709-708 C_node710-735 C_node710-736 C_node711-741 C_node711-740 C_node713-704 C_node714-718 C_node720-707 C_node720-706 C_node727-744 C_node730-709 C_node733-734 C_node734-737 C_node734-710 C_node737-738 C_node738-711 C_node744-728 C_node781-701 C_node744-729 A_xform709-775 B_xform709-775 C_xform709-775 A_node701-702 A_node702-705 A_node702-713 A_node702-703 A_node703-727 A_node703-730 A_node704-714 A_node704-720 A_node707-724 A_node707-722 A_node708-733 A_node708-732 A_node709-731 A_node709-708 A_node710-735 A_node710-736 A_node711-741 A_node711-740 A_node713-704 A_node714-718 A_node720-707 A_node720-706 A_node727-744 A_node730-709
Data Validation Checks on Line Hardening and Construction options completed... success
Data Validation Checks on Load completed... success
Data Validation Checks on cycles completed... success
Data Validation Checks on islands... fail
	The network model has islands. RDT can handle islands, but infeasible cases can occur if load is isolated from generators.
	Islands include:
		 C_load722_bus C_load724_bus C_load718_bus C_load720_bus C_load713_bus C_load714_bus C_load701_bus C_load712_bus C_load725_bus C_load727_bus C_load733_bus C_load731_bus C_load728_bus C_node781_bus C_load734_bus C_load729_bus C_load737_bus C_load736_bus C_load735_bus C_load730_bus C_load744_bus C_node775_bus C_load738_bus C_load740_bus C_load741_bus C_load742_bus C_load732_bus C_node703_bus C_node702_bus C_node705_bus C_node704_bus C_node707_bus C_node706_bus C_node709_bus C_node708_bus C_node711_bus C_node710_bus
		 B_node709_bus B_node708_bus B_node707_bus B_node706_bus B_load712_bus B_load701_bus B_node711_bus B_node710_bus B_load714_bus B_load713_bus B_node781_bus B_node702_bus B_node703_bus B_node704_bus B_node705_bus B_load729_bus B_load718_bus B_load720_bus B_load728_bus B_load727_bus B_load722_bus B_load744_bus B_node775_bus B_load724_bus B_load733_bus B_load732_bus B_load735_bus B_load734_bus B_load737_bus B_load736_bus B_load740_bus B_load738_bus B_load742_bus B_load741_bus B_load730_bus B_load731_bus B_load725_bus
		 A_load722_bus A_load724_bus A_node709_bus A_node708_bus A_node705_bus A_node704_bus A_node707_bus A_node706_bus A_node781_bus A_node703_bus A_node702_bus A_load720_bus A_node775_bus A_load738_bus A_load736_bus A_load737_bus A_load744_bus A_load742_bus A_node710_bus A_load701_bus A_load712_bus A_load713_bus A_load714_bus A_load718_bus A_load733_bus A_load732_bus A_load731_bus A_load730_bus A_load729_bus A_load728_bus A_load727_bus A_load725_bus A_load735_bus A_load734_bus
		 A_load740_bus A_load741_bus A_node711_bus
Data Validation Checks on available generation completed... success
Data Validation Checks on Line Connectivity... success
Data Validation Checks on RDT completed.

**Comment by rb004f** [comment]
Ok, we'll figure this out.  The SCIP installation instructions are based on what we figured out what was required for a fresh install of Ubuntu 16.04.1 18 months ago. If Ubuntu has changed its support of these libraries, I expect we'll need to introduce a manual step to get the libraries. (like here https://ubuntu.pkgs.org/16.04/ubuntu-main-i386/libreadline6-dev_6.3-8ubuntu2_i386.deb.html)

Just to confirm, you followed these instructions and it failed on libreadline6 and libreadline6-dev?


``
apt-get update
apt-get -y upgrade
apt-get -y install gcc g++ gfortran libreadline-dev libgmp-dev zlib1g-dev libncurses-dev make cmake wget libreadline6 libreadline6-dev
``

Also, if SCIP not installed, then you will not get any output since SCIP is needed to generate the solutions that go into the output.  Based on the console output I am seeing, it looks like this is the case.  So don't spend any more time on that.  We need to get SCIP installed properly and go from there.

**Comment by rb004f** [comment]
What version of ubuntu are you running? It looks like later versions of ubuntu have dropped support for readline6 and have gone to version 7.  We are working on seeing if we can compile a version that does not require version 6.

**Comment by rb004f** [comment]
Ok, I have a version of the library that should be compatible with readline version  7, but I'd like to test it on our side with a clean version of your ubuntu environment.

**Comment by rb004f** [comment]
We have build a version of the library that reduces the dependencies to
apt-get -y install gcc gfortran g++

Let us know how to get it to you

**Comment by OppenheimerAndTheMartians** [comment]
Roger, let me try it out.

**Comment by dpinney** [comment]
Did it work?

**Comment by dpinney** [comment]
Ideally RDT checks the lib versions on startup and shuts down with a human-readable error message if there's a version issue. It appears that it dies with a cryptic exception currently.

**Comment by rb004f** [comment]
We provided a build of the library for unbuntu 18.10. in Dec... once we get confirmation that it also works on your 18.10 we will adjust RDT to generate a better error message.

**Comment by dpinney** [comment]
@OppenheimerAndTheMartians please provide the requested information.

**Comment by OppenheimerAndTheMartians** [comment]
@dpinney @rb004f 

It was working prior to the reboot-the file was being generated. So, if I follow the same steps that I did in December, I should be fine. I'm currently reworking on it, will send confirmation immediately upon success.

**Comment by rb004f** [comment]
Very good. We will update the documentation and error messaging for the required libraries (readline6 is no longer supported in ubuntu) and drop support for ubuntu <= 18.10.

**Comment by OppenheimerAndTheMartians** [comment]
@rb004f @dpinney It's working now. We can consider this issue closed?

**Comment by dpinney** [comment]
What were the steps needed to get it working?

**Comment by rb004f** [comment]
We will update the documentation here and the error checking this week,  The short answer was is that Ubuntu stopped supporting a library between versions 16 and 18..

**Comment by rb004f** [comment]
Documentation updated.  Next step is to produce better error messages

**Comment by dpinney** [comment]
Ian (OppenheimerAndTheMartians) was able to get this working on Ubuntu 18.04. He explained the install process to me, it took about 10 minutes to get through, and I read the readme install doc, but I still am not quite clear on what was fixed or how. This appears to be as good as it's going to get. We can close this issue now.

**Comment by dpinney** [comment]
Recommendation: rename issue to "Install failure on Ubuntu 18.04, like SCIP issue."

**Comment by rb004f** [comment]
Closing the ticket.  The shortest answer is that the build of SCIP required libreadline.so.6.  In unbuntu 18.X apt-get libreadline-dev stopped installing this library--instead installing libreadline.so.7. So, we had to figure out how to build SCIP with a dependency on libreadline.so.7. We have not figured out how to modify SCIP's makefile to build a binary with all dependencies embedded.
